### ISSUE TITLE
GeoFlutterFire Failing on Run

### ISSUE THREAD

**Issue by austinmccalley** [DarshanGowda0/GeoFlutterFire#32]
I am trying to build an app using GeoFlutterFire and it keeps on failing on build.

Output of flutter doctor -v
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/austin/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /usr/local/share/android-sdk
      but Android SDK not found at this location.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.26.1
```

Pubspec.yaml Dependencies
```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.4
  cloud_firestore: ^0.9.13+1
  # firebase_analytics: ^2.1.1+3
  rxdart: ^0.21.0

  # geoflutterfire: ^2.0.3
  geoflutterfire:
    git: git://github.com/DarshanGowda0/GeoFlutterFire.git
  location: ^2.3.5
  google_maps_flutter: ^0.2.0
```
Output of flutter build -v
https://gist.github.com/Mr-Que/fcf2b1a3f67c5fa84ef05deec2009eed
