### ISSUE TITLE
Duplicate data in the result

### ISSUE THREAD

**Issue by KasemJaffer** [DarshanGowda0/GeoFlutterFire#57]
I am getting duplicate data result.

Here is my code:
```dart
// I only have one 
GeoFlutterfire()
        .collection(
            collectionRef: Firestore.instance.collection('countries'))
        .within(
            center: GeoFirePoint(45.208794, -133.5497394),
            radius: 50000,
            field: "location",
            strictMode: true).listen((snapshots){
int count = snapshots.length; // snapshots has two items of the same document.
};
```

**Comment by marvinsxtr** [comment]
Interestingly, I found the same behavior for any radius value over 1250. Below this number, everything works fine for me.

**Comment by Thibault2ss** [comment]
Hey everyone, I had the same issue, I found the bug and fixed it. It was because of an edge case not handled by the lib, which created a duplicate query.

To fix it (until @DarshanGowda0 merges my fix) you can update your **pubspec.yaml** file to fetch my fixed branch:
```yaml
geoflutterfire:
    git:
      url: git://github.com/Thibault2ss/GeoFlutterFire
      ref: fix-duplicate-results-on-large-radius
```

Cheers 👍
